server:
  port: 8082

spring:
  application:
    name: profile-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ride_hailing
    username: rh_user
    password: rh_password
    pool:
      initial-size: 5
      max-size: 20
  flyway:
    url: jdbc:postgresql://localhost:5432/ride_hailing
    user: rh_user
    password: rh_password
    locations: classpath:db/migration
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.springframework.r2dbc: INFO
    org.flywaydb: INFO
    org.apache.kafka: INFO
