global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "auth"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth:8081"]

  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8080"]
