server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379

  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:

        # Authenticated /auth endpoints
        - id: auth-me
          uri: https://auth:8080
          predicates:
            - Path=/auth/me
          filters:
            - JwtAuth

        - id: auth-sessions
          uri: https://auth:8080
          predicates:
            - Path=/auth/sessions,/auth/sessions/**
          filters:
            - JwtAuth

        # Public /auth endpoints
        - id: auth-public
          uri: https://auth:8080
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie



        - id: secure-info
          uri: https://auth:8080
          predicates:
            - Path=/secure/info
          filters:
            - JwtAuth

        # Profile service
        - id: profile-service
          uri: http://profile:8080
          predicates:
            - Path=/profile/**
          filters:
            - JwtAuth
            - PreserveHostHeader
            # - SetRequestHeader=X-Forwarded-Proto, http

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true
