server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      # âœ” correct syntax
      default-filters:
        - JwtAuth

      routes:
        - id: auth
          uri: http://auth:8081
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: secure-info
          uri: http://auth:8081
          predicates:
            - Path=/secure/info
          filters:
            - JwtAuth

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
